# Generated by Django 2.1 on 2020-05-13 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('progress', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('congress_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(default=0, max_length=50)),
                ('importance', models.IntegerField()),
                ('address', models.CharField(default=0, max_length=400)),
                ('phone', models.CharField(default=0, max_length=20)),
                ('bills', models.ManyToManyField(to='example.bill')),
            ],
        ),
        migrations.CreateModel(
            name='congress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=400)),
                ('party', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('house', models.BooleanField()),
                ('website', models.CharField(max_length=150)),
                ('imageLink', models.CharField(max_length=150)),
                ('congress_num', models.IntegerField()),
                ('congresslink', models.CharField(default='', max_length=150)),
                ('served', models.CharField(default='', max_length=150)),
                ('bills', models.ManyToManyField(to='example.bill')),
            ],
        ),
        migrations.CreateModel(
            name='sub_committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('committee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='example.committee')),
                ('members', models.ManyToManyField(to='example.congress')),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(to='example.congress'),
        ),
    ]
