# Generated by Django 3.0.6 on 2020-05-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='chamber',
            field=models.CharField(default='', max_length=100),
        ),
    ]
