# Generated by Django 3.0.6 on 2020-05-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_bill_chamber'),
    ]

    operations = [
        migrations.AddField(
            model_name='congress',
            name='cosponsored',
            field=models.ManyToManyField(related_name='cosponsored', to='example.bill'),
        ),
    ]
