# Generated by Django 3.0.6 on 2020-05-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_congress_cosponsored'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='pdflink',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='committee',
            name='link',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='sub_committee',
            name='link',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
