# Generated by Django 2.1 on 2020-05-10 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_auto_20200510_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='committee',
            old_name='importantce',
            new_name='importance',
        ),
        migrations.AddField(
            model_name='committee',
            name='address',
            field=models.CharField(default=0, max_length=400),
        ),
        migrations.AddField(
            model_name='committee',
            name='location',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='committee',
            name='phone',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='committee',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='sub_committee',
            name='committee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='example.committee'),
        ),
        migrations.AddField(
            model_name='sub_committee',
            name='members',
            field=models.ManyToManyField(to='example.congress'),
        ),
    ]
