# Generated by Django 3.0.6 on 2020-05-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_auto_20200519_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='congress',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
